import '../features/products/domain/entities/product_entity.dart';
import '../features/products/domain/entities/category_entity.dart';

class MockData {  static List<ProductEntity> get products => [
    // Hambúrguers
    ProductEntity(
      id: '1',
      name: 'Hambúrguer Clássico',
      description: 'Hambúrguer artesanal com queijo, alface e tomate',
      price: 25.90,
      categoryId: 'hamburgers',
      imageUrl: 'assets/images/Hamburgueres/hamburguer_clássico.png',
      isAvailable: true,
      availableQuantity: 10,
    ),
    ProductEntity(
      id: '2',
      name: 'Cheese Burger',
      description: 'Hambúrguer com queijo derretido e molho especial',
      price: 28.90,
      categoryId: 'hamburgers',
      imageUrl: 'assets/images/Hamburgueres/cheese_burger.png',
      isAvailable: true,
      availableQuantity: 8,
    ),
    ProductEntity(
      id: '3',
      name: 'Double Burger',
      description: 'Hambúrguer duplo com dois hambúrguers suculentos',
      price: 35.90,
      categoryId: 'hamburgers',
      imageUrl: 'assets/images/Hamburgueres/double_burger.png',
      isAvailable: true,
      availableQuantity: 6,
    ),
    ProductEntity(
      id: '4',
      name: 'Double Cheese Burger',
      description: 'Hambúrguer duplo com queijo derretido',
      price: 39.90,
      categoryId: 'hamburgers',
      imageUrl: 'assets/images/Hamburgueres/double_cheese_burger.png',
      isAvailable: true,
      availableQuantity: 7,
    ),
    ProductEntity(
      id: '5',
      name: 'Jumbo Cheese Burger',
      description: 'Hambúrguer gigante com muito queijo',
      price: 45.90,
      categoryId: 'hamburgers',
      imageUrl: 'assets/images/Hamburgueres/jumbo_cheese_burger.png',
      isAvailable: true,
      availableQuantity: 4,
    ),
    ProductEntity(
      id: '6',
      name: 'Special Cheese Burger',
      description: 'Hambúrguer especial com queijo premium',
      price: 42.90,
      categoryId: 'hamburgers',
      imageUrl: 'assets/images/Hamburgueres/special_cheese_burger.png',
      isAvailable: true,
      availableQuantity: 5,
    ),
    ProductEntity(
      id: '7',
      name: 'Spicy Burger',
      description: 'Hambúrguer picante com pimenta e molho apimentado',
      price: 32.90,
      categoryId: 'hamburgers',
      imageUrl: 'assets/images/Hamburgueres/spicy_burger.png',
      isAvailable: true,
      availableQuantity: 8,
    ),
    
    // Pizzas
    ProductEntity(
      id: '8',
      name: 'Pizza Margherita',
      description: 'Pizza tradicional com molho de tomate, mussarela e manjericão',
      price: 32.50,
      categoryId: 'pizzas',
      imageUrl: 'assets/images/Pizzas/pizza_magherita.png',
      isAvailable: true,
      availableQuantity: 8,
    ),
    ProductEntity(
      id: '9',
      name: 'Pizza Calabresa',
      description: 'Pizza com calabresa, cebola e azeitonas',
      price: 35.00,
      categoryId: 'pizzas',
      imageUrl: 'assets/images/Pizzas/pizza_calabresa.png',
      isAvailable: true,
      availableQuantity: 6,
    ),
    ProductEntity(
      id: '10',
      name: 'Pizza Portuguesa',
      description: 'Pizza com presunto, ovos, ervilha e cebola',
      price: 38.50,
      categoryId: 'pizzas',
      imageUrl: 'assets/images/Pizzas/pizza_portuguesa.png',
      isAvailable: true,
      availableQuantity: 4,
    ),
    
    // Bebidas
    ProductEntity(
      id: '11',
      name: 'Coca-Cola Lata',
      description: 'Refrigerante gelado em lata 350ml',
      price: 5.00,
      categoryId: 'drinks',
      imageUrl: 'assets/images/Bebidas/coca_cola_lata.png',
      isAvailable: true,
      availableQuantity: 20,
    ),
    ProductEntity(
      id: '12',
      name: 'Suco de Laranja',
      description: 'Suco natural de laranja 300ml',
      price: 8.50,
      categoryId: 'drinks',
      imageUrl: 'assets/images/Bebidas/suco_de_laranja.png',
      isAvailable: true,
      availableQuantity: 15,
    ),
  ];

  static List<CategoryEntity> get categories => [
    CategoryEntity(
      id: 'hamburgers',
      name: 'Hambúrguers',
      description: 'Deliciosos hambúrguers artesanais',
      iconPath: 'assets/icons/hamburger.png',
    ),
    CategoryEntity(
      id: 'pizzas',
      name: 'Pizzas',
      description: 'Pizzas tradicionais e especiais',
      iconPath: 'assets/icons/pizza.png',
    ),
    CategoryEntity(
      id: 'drinks',
      name: 'Bebidas',
      description: 'Refrigerantes, sucos e bebidas geladas',
      iconPath: 'assets/icons/drink.png',
    ),
  ];
}
